name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - name: Upload MalumMenu.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: MalumMenu.dll
          path: /home/runner/work/MalumMenu/MalumMenu/src/bin/Release/net6.0/MalumMenu.dll

      - name: Download and extract BepInEx
        run: |
          wget -O BepInEx_x64.zip https://builds.bepinex.dev/projects/bepinex_be/735/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.735%2B5fef357.zip
          unzip BepInEx_x64.zip -d BepInEx_x64
          wget -O BepInEx_x86.zip https://builds.bepinex.dev/projects/bepinex_be/735/BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.735%2B5fef357.zip
          unzip BepInEx_x86.zip -d BepInEx_x86

      - name: Copy MalumMenu.dll to BepInEx/plugins
        run: |
          chmod -R 755 BepInEx_x86
          chmod -R 755 BepInEx_x64
          cp /home/runner/work/MalumMenu/MalumMenu/src/bin/Release/net6.0/MalumMenu.dll BepInEx_x86/BepInEx/plugins/
          cp /home/runner/work/MalumMenu/MalumMenu/src/bin/Release/net6.0/MalumMenu.dll BepInEx_x64/BepInEx/plugins/

      - name: Upload MalumMenu_Steam_Itch.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: MalumMenu_Steam_Itch
          path: BepInEx_x86

      - name: Upload MalumMenu_EpicGames_MicrosoftStore_XboxApp.zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: MalumMenu_EpicGames_MicrosoftStore_XboxApp
          path: BepInEx_x64